# Generated by Django 4.1.5 on 2023-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competenceprofile', '0002_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='abilities',
            field=models.ManyToManyField(related_name='knowledges', to='competenceprofile.ability'),
        ),
    ]
