# Generated by Django 4.1.5 on 2023-11-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_process_stage'),
        ('competenceprofile', '0003_alter_knowledge_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='processes',
            field=models.ManyToManyField(related_name='processes', to='products.process'),
        ),
        migrations.CreateModel(
            name='ProcessAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_position', models.IntegerField()),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competenceprofile.ability')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.process')),
            ],
        ),
    ]
