# Generated by Django 4.1.5 on 2023-11-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competenceprofile', '0004_alter_ability_processes_processability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='processes',
        ),
    ]
