# Generated by Django 4.1.5 on 2023-11-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competenceprofile', '0006_ability_processes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='processes',
        ),
    ]
