# Generated by Django 4.1.5 on 2023-11-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_process_stage'),
        ('competenceprofile', '0007_remove_ability_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='processes',
            field=models.ManyToManyField(related_name='abilities', through='competenceprofile.ProcessAbility', to='products.process'),
        ),
    ]
