# Generated by Django 4.1.5 on 2023-11-24 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competenceprofile', '0008_ability_processes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='abilities',
        ),
        migrations.CreateModel(
            name='AbilityKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ak_position', models.IntegerField()),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competenceprofile.ability')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competenceprofile.knowledge')),
            ],
        ),
    ]
