# Generated by Django 4.1.5 on 2023-11-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competenceprofile', '0009_remove_knowledge_abilities_abilityknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='abilities',
            field=models.ManyToManyField(related_name='knowledges', through='competenceprofile.AbilityKnowledge', to='competenceprofile.ability'),
        ),
    ]
