# Generated by Django 4.1.5 on 2023-11-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
