# Generated by Django 5.0.6 on 2024-12-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
