# Generated by Django 4.1.5 on 2023-11-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0007_programuser_program_id_programuser_role_id_and_more'),
        ('competenceprofile', '0003_alter_knowledge_abilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('knowledges', models.ManyToManyField(related_name='disciplines', to='competenceprofile.knowledge')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='programs.program')),
            ],
        ),
    ]
