# Generated by Django 4.1.5 on 2023-11-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competenceprofile', '0003_alter_knowledge_abilities'),
        ('disciplines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='knowledges',
        ),
        migrations.CreateModel(
            name='DisciplineKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplines.discipline')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competenceprofile.knowledge')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competenceprofile.ability')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplines.discipline')),
            ],
        ),
    ]
