# Generated by Django 4.1.5 on 2023-11-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competenceprofile', '0003_alter_knowledge_abilities'),
        ('disciplines', '0002_remove_discipline_knowledges_disciplineknowledge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='abilities',
            field=models.ManyToManyField(related_name='disciplines', through='disciplines.DisciplineAbility', to='competenceprofile.ability'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='knowledges',
            field=models.ManyToManyField(related_name='disciplines', through='disciplines.DisciplineKnowledge', to='competenceprofile.knowledge'),
        ),
    ]
