# Generated by Django 4.1.5 on 2023-12-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_programuser_program_id_programuser_role_id_and_more'),
        ('disciplines', '0004_rename_position_disciplineability_da_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SemesterDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(max_length=20, null=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplines.discipline')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplines.semester')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='disciplines',
            field=models.ManyToManyField(related_name='semesters', through='disciplines.SemesterDiscipline', to='disciplines.discipline'),
        ),
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='programs.program'),
        ),
    ]
