# Generated by Django 4.1.5 on 2024-03-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_process_stage'),
        ('disciplines', '0006_semesterdiscipline_sd_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='processes',
            field=models.ManyToManyField(related_name='disciplines', to='products.process'),
        ),
    ]
