# Generated by Django 5.0.6 on 2025-01-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0007_discipline_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterdiscipline',
            name='zet',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
