# Generated by Django 4.1.5 on 2023-11-02 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0002_educationlevel_alter_direction_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=255)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.direction')),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='programs.educationlevel')),
            ],
            options={
                'db_table': 'programs',
            },
        ),
    ]
