# Generated by Django 4.1.5 on 2023-11-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='direction',
            new_name='direction_id',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='level',
            new_name='level_id',
        ),
    ]
