# Generated by Django 4.1.5 on 2023-11-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_programrole_programuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programuser',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='programuser',
            name='user',
        ),
    ]
