# Generated by Django 4.1.5 on 2023-11-03 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0006_remove_programuser_program_remove_programuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programuser',
            name='program_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programuser',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programrole'),
        ),
        migrations.AddField(
            model_name='programuser',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
