# Generated by Django 4.1.5 on 2023-12-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_programuser_program_id_programuser_role_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='form',
            field=models.CharField(choices=[('Очная', 'Очная'), ('Очно-заочная', 'Очно-заочная'), ('Заочная', 'Заочная')], default='Очная', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='max_semesters',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
