# Generated by Django 4.1.5 on 2024-05-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_program_form_program_max_semesters'),
    ]

    operations = [
        migrations.CreateModel(
            name='NsiType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField()),
                ('part', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип НСИ',
                'verbose_name_plural': 'Типы НСИ',
                'ordering': ['position'],
            },
        ),
    ]
