# Generated by Django 4.1.5 on 2024-05-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_nsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsi',
            name='program_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
        ),
    ]
