# Generated by Django 4.1.5 on 2024-05-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_nsi_program_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsi',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='nsi',
            old_name='program_id',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='nsi',
            old_name='type_id',
            new_name='type',
        ),
    ]
