# Generated by Django 4.1.5 on 2024-06-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_rename_author_id_nsi_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsi',
            name='accept_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='accept_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiApproveName',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiAuthors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiBasis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiCity',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiCode',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiEdit',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiEditor',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiMinistry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.ministry'),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiNumber',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiPages',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiPeriod',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiProtocolDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiProtocolNumber',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='nsiYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='old_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nsi',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
