# Generated by Django 5.0.6 on 2024-11-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_alter_nsi_accept_date_alter_nsi_accept_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
