from django.core.management.base import BaseCommand
from programs.models import NsiType


class Command(BaseCommand):
    help = 'Создаем типы НСИ'

    def handle(self, *args, **kwargs):
        nsi_types_data = [
                {'id': 1, 'name': 'Нормативно-техническая документация, ГОСТы', 'created_at': None, 'updated_at': None,
                 'position': 0, 'part': 0, 'active': False, 'description': None, 'code': '-'},
                {'id': 2, 'name': 'Учебники, монографии', 'created_at': None, 'updated_at': None, 'position': 0,
                 'part': 0, 'active': False, 'description': None, 'code': '-'},
                {'id': 3, 'name': 'Интернет ресурсы', 'created_at': None, 'updated_at': None, 'position': 0,
                 'part': 0, 'active': False, 'description': None, 'code': '-'},
                {'id': 4, 'name': 'Электронно-библиотечная система', 'created_at': None, 'updated_at': None,
                 'position': 0, 'part': 0, 'active': False, 'description': None, 'code': '-'},
                {'id': 5, 'name': 'Нормативно-правовые акты', 'created_at': None, 'updated_at': None, 'position': 0,
                 'part': 0, 'active': False, 'description': None, 'code': '-'},
                {'id': 6, 'name': 'Отраслевые дорожные методические документы', 'created_at': None, 'updated_at': None,
                 'position': 0, 'part': 0, 'active': False, 'description': None, 'code': '-'},
                {'id': 8, 'name': 'Иные источники', 'created_at': None, 'updated_at': None, 'position': 0,
                 'part': 0, 'active': False, 'description': None, 'code': '-'},
                {'id': 9, 'name': 'Федеральный закон', 'created_at': None, 'updated_at': None, 'position': 5, 'part': 1,
                 'active': True, 'description': None, 'code': 'fz'},
                {'id': 10, 'name': 'Закон РФ', 'created_at': None, 'updated_at': None, 'position': 6, 'part': 1,
                 'active': True, 'description': None, 'code': 'zrf'},
                {'id': 11, 'name': 'Кодекс РФ', 'created_at': None, 'updated_at': None, 'position': 4, 'part': 1,
                 'active': True, 'description': None, 'code': 'krf'},
                {'id': 12, 'name': 'Указ Президента РФ', 'created_at': None, 'updated_at': None, 'position': 9,
                 'part': 1, 'active': True, 'description': None, 'code': 'yrf'},
                {'id': 13, 'name': 'Постановление Правительства РФ', 'created_at': None, 'updated_at': None,
                 'position': 10, 'part': 1, 'active': True, 'description': None, 'code': 'pprf'},
                {'id': 14, 'name': 'Распоряжение Правительства РФ', 'created_at': None, 'updated_at': None,
                 'position': 11, 'part': 1, 'active': True, 'description': None, 'code': 'rprf'},
                {'id': 15, 'name': 'Паспорт национального проекта', 'created_at': None, 'updated_at': None,
                 'position': 21, 'part': 1, 'active': True, 'description': None, 'code': 'pnp'},
                {'id': 16, 'name': 'Поручение Президента РФ', 'created_at': None, 'updated_at': None, 'position': 20,
                 'part': 1, 'active': True, 'description': None, 'code': 'porprf'},
                {'id': 17, 'name': 'Паспорт федерального проекта', 'created_at': None, 'updated_at': None,
                 'position': 22, 'part': 1, 'active': True, 'description': None, 'code': 'pfp'},
                {'id': 18, 'name': 'Паспорт проекта', 'created_at': None, 'updated_at': None, 'position': 23, 'part': 1,
                 'active': True, 'description': None, 'code': 'pp'},
                {'id': 19, 'name': 'Порядок', 'created_at': None, 'updated_at': None, 'position': 24, 'part': 1,
                 'active': True, 'description': None, 'code': 'p'},
                {'id': 20, 'name': 'Регламент', 'created_at': None, 'updated_at': None, 'position': 25, 'part': 1,
                 'active': True, 'description': None, 'code': 'r'},
                {'id': 21, 'name': 'Технический регламент таможенного союза', 'created_at': None, 'updated_at': None,
                 'position': 27, 'part': 1, 'active': True, 'description': None, 'code': 'trts'},
                {'id': 22, 'name': 'Постановление Госстроя России', 'created_at': None, 'updated_at': None,
                 'position': 16, 'part': 1, 'active': True, 'description': None, 'code': 'pgr'},
                {'id': 23, 'name': 'Приказ Минобрнауки России', 'created_at': None, 'updated_at': None, 'position': 15,
                 'part': 1, 'active': False, 'description': None, 'code': 'pmor'},
                {'id': 24, 'name': 'Приказ Минтранса России', 'created_at': None, 'updated_at': None, 'position': 16,
                 'part': 1, 'active': False, 'description': None, 'code': 'pmtr'},
                {'id': 25, 'name': 'Приказ Госстроя России', 'created_at': None, 'updated_at': None, 'position': 17,
                 'part': 1, 'active': True, 'description': None, 'code': 'prgr'},
                {'id': 26, 'name': 'Приказ Минстроя России', 'created_at': None, 'updated_at': None, 'position': 18,
                 'part': 1, 'active': False, 'description': None, 'code': 'pmsr'},
                {'id': 27, 'name': 'Приказ Федеральной службы', 'created_at': None, 'updated_at': None, 'position': 14,
                 'part': 1, 'active': True, 'description': None, 'code': 'pfs'},
                {'id': 28, 'name': 'Распоряжение Минобрнауки России', 'created_at': None, 'updated_at': None,
                 'position': 20, 'part': 1, 'active': False, 'description': None, 'code': 'rmor'},
                {'id': 29, 'name': 'Распоряжение Минтранса России', 'created_at': None, 'updated_at': None,
                 'position': 21, 'part': 1, 'active': False, 'description': None, 'code': 'rmtr'},
                {'id': 30, 'name': 'Распоряжение Минстроя России', 'created_at': None, 'updated_at': None,
                 'position': 22, 'part': 1, 'active': False, 'description': None, 'code': 'rmsr'},
                {'id': 31, 'name': 'Распоряжение Федеральной службы', 'created_at': None, 'updated_at': None,
                 'position': 18, 'part': 1, 'active': True, 'description': None, 'code': 'rfs'},
                {'id': 32, 'name': 'Методические рекомендации', 'created_at': None, 'updated_at': None, 'position': 39,
                 'part': 1, 'active': True, 'description': None, 'code': 'mr'},
                {'id': 33, 'name': 'Примерная программа', 'created_at': None, 'updated_at': None, 'position': 41,
                 'part': 1, 'active': True, 'description': None, 'code': 'prp'},
                {'id': 35, 'name': 'Требования', 'created_at': None, 'updated_at': None, 'position': 26, 'part': 1,
                 'active': True, 'description': None, 'code': 't'},
                {'id': 36, 'name': 'Каталог', 'created_at': None, 'updated_at': None, 'position': 40, 'part': 1, 'active': True, 'description': None, 'code': 'k'},
                {'id': 37, 'name': 'ГОСТ Р', 'created_at': None, 'updated_at': None, 'position': 29, 'part': 1, 'active': True, 'description': 'Национальный (государственный) стандарт', 'code': 'gostr'},
                {'id': 38, 'name': 'ГОСТ', 'created_at': None, 'updated_at': None, 'position': 30, 'part': 1, 'active': True, 'description': 'Межгосударственный стандарт', 'code': 'gost'},
                {'id': 39, 'name': 'ОДМ', 'created_at': None, 'updated_at': None, 'position': 31, 'part': 1, 'active': True, 'description': 'Отраслевой дорожный методический документ', 'code': 'odm'},
                {'id': 40, 'name': 'СТО', 'created_at': None, 'updated_at': None, 'position': 32, 'part': 1, 'active': True, 'description': 'Стандарт организации', 'code': 'sto'},
                {'id': 41, 'name': 'СПО', 'created_at': None, 'updated_at': None, 'position': 33, 'part': 1, 'active': True, 'description': 'Свод правил организации', 'code': 'spo'},
                {'id': 42, 'name': 'ГСН', 'created_at': None, 'updated_at': None, 'position': 34, 'part': 1, 'active': True, 'description': 'Государственные сметные нормы', 'code': 'gsn'},
                {'id': 43, 'name': 'СНиП', 'created_at': None, 'updated_at': None, 'position': 35, 'part': 1, 'active': True, 'description': 'Строительные нормы и правила', 'code': 'snip'},
                {'id': 44, 'name': 'СП', 'created_at': None, 'updated_at': None, 'position': 36, 'part': 1, 'active': True, 'description': 'Свод правил', 'code': 'sp'},
                {'id': 45, 'name': 'ЕНИР', 'created_at': None, 'updated_at': None, 'position': 37, 'part': 1, 'active': True, 'description': 'Единые нормы и расценки', 'code': 'enir'},
                {'id': 46, 'name': 'ТУ', 'created_at': None, 'updated_at': None, 'position': 38, 'part': 1, 'active': True, 'description': 'Технические условия', 'code': 'ty'},
                {'id': 47, 'name': 'ISO', 'created_at': None, 'updated_at': None, 'position': 28, 'part': 1, 'active': True, 'description': 'Международные стандарты', 'code': 'iso'},
                {'id': 48, 'name': 'Учебники, монографии', 'created_at': None, 'updated_at': None, 'position': 40, 'part': 2, 'active': True, 'description': None, 'code': 'book'},
                {'id': 49, 'name': 'ПНСТ', 'created_at': None, 'updated_at': None, 'position': 41, 'part': 3, 'active': True, 'description': 'Предварительный национальный стандарт', 'code': 'pnst'},
                {'id': 50, 'name': 'Официальный сайт', 'created_at': None, 'updated_at': None, 'position': 42, 'part': 3, 'active': True, 'description': None, 'code': 'site'},
                {'id': 51, 'name': 'Приказ Росстата', 'created_at': None, 'updated_at': None, 'position': 15, 'part': 1, 'active': True, 'description': None, 'code': 'rosstat'},
                {'id': 52, 'name': 'Локальный акт организации', 'created_at': None, 'updated_at': None, 'position': 19, 'part': 1, 'active': True, 'description': None, 'code': 'local'},
                {'id': 53, 'name': 'Статья из журнала', 'created_at': None, 'updated_at': None, 'position': 44, 'part': 4, 'active': True, 'description': None, 'code': 'sis'},
                {'id': 54, 'name': 'Статья из сборника', 'created_at': '2022-07-28 12:03:06', 'updated_at': '2022-07-28 12:03:06', 'position': 45, 'part': 4, 'active': True, 'description': None, 'code': 'sig'},
                {'id': 55, 'name': 'Приказ Министерства', 'created_at': '2022-07-28 14:54:07', 'updated_at': '2022-07-28 14:54:07', 'position': 12, 'part': 1, 'active': True, 'description': None, 'code': 'prmin'},
                {'id': 56, 'name': 'Распоряжение Министерства', 'created_at': '2022-07-28 16:17:40', 'updated_at': '2022-07-28 16:28:27', 'position': 13, 'part': 1, 'active': True, 'description': None, 'code': 'rmin'},
                {'id': 57, 'name': 'Международный документ', 'created_at': '2022-07-28 16:28:26', 'updated_at': '2022-07-28 16:28:27', 'position': 2, 'part': 1, 'active': True, 'description': None, 'code': 'megdoc'},
                {'id': 58, 'name': 'Другое', 'created_at': None, 'updated_at': None, 'position': 42, 'part': 1, 'active': True, 'description': None, 'code': 'dr'}
            ]

        nsi_types = [NsiType(**data) for data in nsi_types_data]
        NsiType.objects.bulk_create(nsi_types)
        self.stdout.write(self.style.SUCCESS('Successfully loaded nsi_types'))
