# Generated by Django 4.1.5 on 2023-11-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_program_product_program_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="program_id",
            new_name="program",
        ),
    ]
