# Generated by Django 4.1.5 on 2023-11-07 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_process_lifestage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.lifestage'),
        ),
    ]
