# Generated by Django 4.1.5 on 2023-11-07 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_programuser_program_id_programuser_role_id_and_more'),
        ('products', '0005_alter_process_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='programs.program'),
        ),
    ]
