# Generated by Django 4.1.5 on 2023-11-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifestage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='products.product'),
        ),
    ]
