# Generated by Django 4.1.5 on 2023-11-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_lifestage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='products.lifestage'),
        ),
    ]
