# Generated by Django 4.1.5 on 2024-04-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_processresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='processresult',
            name='base',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processresult',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
