# Generated by Django 5.0.6 on 2025-01-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_processresult_base_processresult_description'),
        ('programs', '0015_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestage',
            name='nsis',
            field=models.ManyToManyField(blank=True, related_name='stages', to='programs.nsi'),
        ),
        migrations.AddField(
            model_name='process',
            name='nsis',
            field=models.ManyToManyField(blank=True, related_name='processes', to='programs.nsi'),
        ),
        migrations.AddField(
            model_name='product',
            name='nsis',
            field=models.ManyToManyField(blank=True, related_name='products', to='programs.nsi'),
        ),
    ]
